RUN adduser --disabled-password --gecos '' flaskuser

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

USER flaskuser

EXPOSE 5000

CMD ["python", "app/app.py"]
